// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHBQu2kzl5XgXAZ-IdSeBBQVUQTMrrPs',
    appId: '1:438950637905:web:e8da075585d9f501556370',
    messagingSenderId: '438950637905',
    projectId: 'flutter-chat-app-5cfcc',
    authDomain: 'flutter-chat-app-5cfcc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5cfcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8eWh6ZmoVYXwyGP-X6IMj7iQcKXGd9pE',
    appId: '1:438950637905:android:3cfc21bb589608c0556370',
    messagingSenderId: '438950637905',
    projectId: 'flutter-chat-app-5cfcc',
    storageBucket: 'flutter-chat-app-5cfcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGeStTRRNtH0R8c_DC2KLyqdmbmOGxn7A',
    appId: '1:438950637905:ios:6a0674195fc459ef556370',
    messagingSenderId: '438950637905',
    projectId: 'flutter-chat-app-5cfcc',
    storageBucket: 'flutter-chat-app-5cfcc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGeStTRRNtH0R8c_DC2KLyqdmbmOGxn7A',
    appId: '1:438950637905:ios:6a0674195fc459ef556370',
    messagingSenderId: '438950637905',
    projectId: 'flutter-chat-app-5cfcc',
    storageBucket: 'flutter-chat-app-5cfcc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbHBQu2kzl5XgXAZ-IdSeBBQVUQTMrrPs',
    appId: '1:438950637905:web:1c59488e447eb043556370',
    messagingSenderId: '438950637905',
    projectId: 'flutter-chat-app-5cfcc',
    authDomain: 'flutter-chat-app-5cfcc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5cfcc.firebasestorage.app',
  );

}